server.port=8080

#Spring Data JPA
spring.datasource.url=jdbc:postgresql://dpg-d85tga8js32c73aov460-a:5432/piplop_play_db
spring.datasource.username=leonardo
spring.datasource.password=ofvMSep4rI1uAye8sq7SwNYUQw4LImtS

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

#LangChain4j
langchain4j.open-ai.chat-model.api-key=demo
